let audioContext;
let analyser;
let dataArray;
let frequencyData;
let sourceNode;
let animationId;
let pitchHistory = [];
let volumeHistory = [];
let lastDisplayUpdate = 0;
let currentPitch = null;
let lastStablePitch = null;
let smoothedPitch = null;
let recentPitchWindow = [];
let pendingPitch = null;
let pendingPitchFrames = 0;
let pitchHoldCounter = 0;
let voicedStable = false;
let voicedFrames = 0;
let voicedLostFrames = 0;
let selectedPitchPoint = null;
let pitchRenderState = null;
let volumeRenderState = null;
let adaptiveNoiseFloorRms = pitchMinEnergyThreshold;
let adaptiveEnergyThreshold = pitchMinEnergyThreshold;
let sessionStartTime = 0;
let pitchAlgorithm = pitchAlgorithmSelect?.value || 'amdf';
let pitchScaleMode = pitchScaleModeSelect?.value || 'log';
let displayMode = displayModeSelect?.value || 'pitch';
let spectrogramOverlayMode = spectrogramOverlaySelect?.value || 'none';
let trainingMode = 'pitch';
let canvasScale = Number(canvasScaleRange?.value || 1);
let spectrogramScrollX = 0;
let lastFormantUpdate = 0;
let lastFormantTimestamp = 0;
let smoothedFormants = { f1: null, f2: null };
let stableFormants = { f1: null, f2: null };
let formantHistory = { f1: [], f2: [] };
let formantCurveHistory = [];
let formantVoiceGate = { frames: 0, lastPitch: null, lostFrames: 0 };
let spectrogramOverlayState = { pitch: null, f1: null, f2: null };
let offlineMode = false;
let offlineAbort = false;
let offlineFormantHistory = [];
let offlineSourceSampleRate = null;
let offlineAnalysisInProgress = false;
let offlineWindowStartMs = 0;
let mediaRecorder = null;
let recordedChunks = [];
let lastRecordingBlob = null;
let recordingStartTime = 0;
let recordingTimelineFrames = [];
let recordingTimelineDurationMs = 0;
let recordingSelectedTimeMs = 0;
let recordingPlaybackAudio = null;
let recordingPlaybackUrl = null;
let recordingPlaybackRaf = null;
let accompanimentAudio = null;
let accompanimentUrl = null;
let accompanimentFile = null;
let targetPitchEnabled = targetPitchToggle?.checked ?? true;
let targetPitchHz = Number(targetPitchInput?.value || 300);
let songPitchTrack = [];
let songPitchFileName = '';
let songPitchEnabled = songPitchToggle?.checked ?? true;
let songPitchAnalysisInProgress = false;
let songPitchAudio = null;
let songPitchAudioUrl = null;
let songPitchPlaybackRaf = null;
let songSearchAbortController = null;
let breathHistory = [];
let breathSessionHistory = [];
let breathRecentScores = [];
let breathCurrentFlow = null;
let breathCurrentEffort = null;
let breathCurrentHighFrequency = null;
let breathCurrentLeakNoise = null;
let breathCurrentStability = null;
let breathStartTime = null;
let breathDurationSeconds = 0;
let breathCalibration = {
  calibrated: false,
  effort: 0,
  highFrequency: 0,
  leakNoise: 0,
  score: 0,
};
let breathCalibrationInProgress = false;
let pitchScoreLastTone = 'neutral';
